name: Generate release pull request

on:
  workflow_dispatch:

jobs:
  generate-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup NPM
        uses: actions/setup-node@v5
        with:
          node-version: '20.x'

      - name: Batch changes
        uses: miniscruff/changie-action@v2
        with:
          version: latest
          args: batch auto

      - name: Merge
        uses: miniscruff/changie-action@v2
        with:
          version: latest
          args: merge

      - name: Latest
        id: latest
        uses: miniscruff/changie-action@v2
        with:
          version: latest
          args: latest

      - name: Run builds
        run: |
          npm install
          npm version --no-git-tag "${{ steps.latest.outputs.output }}"
          npm run build

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GH_PAT }}
          title: Release ${{ steps.latest.outputs.output }}
          branch: release/${{ steps.latest.outputs.output }}
          commit-message: Release ${{ steps.latest.outputs.output }}
          body-path: ".changes/${{ steps.latest.outputs.output }}.md"
